# Generated by Django 6.0.1 on 2026-02-02 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_recipe_instruction_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='stories/')),
                ('role', models.CharField(help_text="e.g., 'Chef', 'Sous Chef', 'Pastry Chef'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'story post',
                'verbose_name_plural': 'story posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
