# Generated by Django 6.0.1 on 2026-02-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_storypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='gluten_free',
            field=models.BooleanField(default=False, help_text='Ricetta senza glutine'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='lactose_free',
            field=models.BooleanField(default=False, help_text='Ricetta senza lattosio'),
        ),
    ]
