# Generated by Django 6.0.1 on 2026-02-02 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_recipe_gluten_free_recipe_lactose_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_likes', to='blog.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'recipe like',
                'verbose_name_plural': 'recipe likes',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'recipe')},
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_recipes', through='blog.RecipeLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
