# Generated by Django 6.0.1 on 2026-02-02 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_recipelike_recipe_liked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate_content', 'Contenuto Inappropriato'), ('spam', 'Spam'), ('misinformation', 'Informazioni Errate'), ('copyright', 'Violazione Copyright'), ('other', 'Altro')], default='inappropriate_content', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Descrizione opzionale del problema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_reports', to='blog.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'recipe report',
                'verbose_name_plural': 'recipe reports',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'recipe')},
            },
        ),
    ]
