# Generated by Django 6.0.1 on 2026-02-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_recipereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipereport',
            name='reason',
            field=models.CharField(choices=[('inappropriate_content', 'Contenuto Inappropriato'), ('spam', 'Spam'), ('copyright', 'Violazione Copyright'), ('other', 'Altro')], default='inappropriate_content', max_length=50),
        ),
    ]
