# Generated by Django 6.0.1 on 2026-02-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_recipereport_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_redazione',
            field=models.BooleanField(default=False, help_text="Profilo Redazione: le ricette pubblicate appariranno con autore 'Redazione'."),
        ),
    ]
