# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_user_is_redazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Ricetta in evidenza: mostrata in homepage. Solo una ricetta può essere in evidenza."),
        ),
    ]
