# Generated by Django (slug support for recipe URLs)

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    Recipe = apps.get_model('blog', 'Recipe')
    for recipe in Recipe.objects.all():
        if not recipe.slug and recipe.title:
            base = slugify(recipe.title) or 'recipe'
            slug = base
            n = 1
            while Recipe.objects.filter(slug=slug).exclude(pk=recipe.pk).exists():
                slug = f'{base}-{n}'
                n += 1
            recipe.slug = slug
            recipe.save(update_fields=['slug'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_recipe_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(generate_slugs, noop),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, db_index=True, max_length=255, null=False, unique=True),
        ),
    ]
