# Generated by Django 6.0.1 on 2026-02-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Ricetta in evidenza: mostrata in homepage. Solo una ricetta può essere in evidenza.', verbose_name='In evidenza'),
        ),
    ]
