# Generated by Django (is_sardinian flag for recipes)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_recipe_final_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_sardinian',
            field=models.BooleanField(default=False, help_text='Ricetta tradizionale sarda'),
        ),
    ]
