# Generated by Django 6.0.1 on 2026-02-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_recipe_is_featured'),
        ('blog', '0011_recipe_final_comment'),
    ]

    operations = [
    ]
