# Generated by Django 6.0.1 on 2026-02-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_merge_20260204_1317'),
        ('blog', '0012_recipe_is_sardinian'),
    ]

    operations = [
    ]
